version: '3.3'

services:
  bot:
    build: .
    container_name: checklist_bot
    restart: unless-stopped 
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PASSWORD=${DB_PASSWORD}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
    networks:
      - checklist_network
    volumes:
      - ./.postgresql/root.crt:/etc/ssl/certs/root.crt:ro
    ports:
      - "8080:8080"

networks:
  checklist_network:
    driver: bridge