version: '3.3'

services:
  bot:
    build: .
    container_name: checklist_bot
    restart: unless-stopped 
    depends_on:
      - db 
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_CONN_STR=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
    networks:
      - checklist_network

  db:
    image: postgres:15-alpine
    container_name: checklist_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - checklist_network
    ports:
     - "5432:5432"

volumes:
  postgres_data:

networks:
  checklist_network:
    driver: bridge