version: '3.3'

services:
  bot:
    build: .
    container_name: checklist_bot
    restart: unless-stopped 
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_CONN_STR=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
    networks:
      - checklist_network

networks:
  checklist_network:
    driver: bridge